<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MMW.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.json" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MMW.Core.Tests" />
  </ItemGroup>
</Project>
