using System.Globalization;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Headless.XUnit;
using Avalonia.LogicalTree;
using Avalonia.Threading;
using MMW.App.Resources;
using MMW.App.Services;
using MMW.App.ViewModels;
using MMW.App.Views;

namespace MMW.App.Tests;

public partial class LocalizationTests
{
    private static readonly string s_resources = Path.Combine(AppContext.BaseDirectory, "Resources");

    private static Dictionary<string, string> ReadResx(string fileName) =>
        XDocument.Load(Path.Combine(s_resources, fileName)).Root!.Elements("data")
            .ToDictionary(d => (string)d.Attribute("name")!, d => (string?)d.Element("value") ?? string.Empty, StringComparer.Ordinal);

    /// <summary>Distinct composite format indices ({0}, {1:0.#}…), ignoring escaped braces.</summary>
    private static int[] Placeholders(string value) =>
        PlaceholderRegex().Matches(value.Replace("{{", string.Empty, StringComparison.Ordinal).Replace("}}", string.Empty, StringComparison.Ordinal))
            .Select(m => int.Parse(m.Groups[1].Value, CultureInfo.InvariantCulture)).Distinct().Order().ToArray();

    [GeneratedRegex(@"\{(\d+)(?:,-?\d+)?(?::[^{}]*)?\}")]
    private static partial Regex PlaceholderRegex();

    public static TheoryData<string> Translations => ["Strings.es.resx"];

    [Theory]
    [MemberData(nameof(Translations))]
    public void Translations_have_the_same_keys_and_placeholders_as_English(string fileName)
    {
        var english = ReadResx("Strings.resx");
        var translated = ReadResx(fileName);

        Assert.Empty(english.Keys.Except(translated.Keys).Order(StringComparer.Ordinal));
        Assert.Empty(translated.Keys.Except(english.Keys).Order(StringComparer.Ordinal));
        foreach (var (key, value) in english)
        {
            Assert.True(Placeholders(value).SequenceEqual(Placeholders(translated[key])),
                $"{key}: '{value}' and '{translated[key]}' use different placeholders.");
            Assert.False(string.IsNullOrWhiteSpace(translated[key]), $"{key} is empty in {fileName}.");
        }
    }

    [Fact]
    public void Every_string_has_a_generated_accessor()
    {
        // Strings.Designer.cs is generated by the IDE from Strings.resx; this catches a stale copy.
        var properties = typeof(Strings).GetProperties(BindingFlags.Public | BindingFlags.Static)
            .Where(p => p.PropertyType == typeof(string)).Select(p => p.Name).ToHashSet(StringComparer.Ordinal);
        Assert.Empty(ReadResx("Strings.resx").Keys.Where(k => !properties.Contains(k)).Order(StringComparer.Ordinal));
        Assert.Empty(properties.Where(p => !ReadResx("Strings.resx").ContainsKey(p)).Order(StringComparer.Ordinal));
    }

    [Fact]
    public void Format_strings_format_in_both_languages()
    {
        var args = Enumerable.Range(0, 5).Select(i => (object)i).ToArray();
        foreach (var culture in new[] { CultureInfo.InvariantCulture, CultureInfo.GetCultureInfo("es") })
        {
            foreach (var key in ReadResx("Strings.resx").Keys.Where(k => k.EndsWith("Format", StringComparison.Ordinal)))
            {
                var format = Strings.ResourceManager.GetString(key, culture)!;
                _ = string.Format(CultureInfo.InvariantCulture, format, args); // throws on a malformed format string
            }
        }
    }

    private static List<string?> MenuHeaders(Window window) =>
        window.GetLogicalDescendants().OfType<Menu>().First().Items.OfType<MenuItem>().Select(m => m.Header as string).ToList();

    private static MainWindow ShowMainWindow()
    {
        var settings = new SettingsService(Path.Combine(Path.GetTempPath(), "mmw-tests", Guid.NewGuid().ToString("N"), "settings.json"));
        var vm = new MainWindowViewModel(new DocumentService(), new FakeDialogService(), settings);
        var window = new MainWindow { DataContext = vm, Width = 1200, Height = 800 };
        window.Show();
        Dispatcher.UIThread.RunJobs();
        return window;
    }

    [AvaloniaFact]
    public void Main_window_is_english_by_default()
    {
        var window = ShowMainWindow();
        Assert.Equal(["_File", "_Edit", "_Metadata", "_Tracks", "_Window", "_Help"], MenuHeaders(window));
        window.Close();
    }

    [AvaloniaFact]
    public void Main_window_follows_the_interface_language()
    {
        var previous = CultureInfo.CurrentUICulture;
        CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("es-ES");
        try
        {
            var window = ShowMainWindow();
            Assert.Equal(["_Archivo", "_Edición", "_Metadatos", "_Pistas", "Ay_uda"], MenuHeaders(window).Where(h => h != "_Ventana"));
            Assert.Contains(window.GetLogicalDescendants().OfType<TextBlock>(), t => t.Text == "Suelta aquí archivos MP4 o Matroska");
            Assert.Equal("Media Metadata Wizard", window.Title);

            var dir = Environment.GetEnvironmentVariable("MMW_SCREENSHOTS") ?? Path.Combine(Path.GetTempPath(), "mmw-screenshots");
            Directory.CreateDirectory(dir);
            window.CaptureRenderedFrame()?.Save(Path.Combine(dir, "13-spanish.png"));
            window.Close();
        }
        finally
        {
            CultureInfo.CurrentUICulture = previous;
        }
    }

    [AvaloniaFact]
    public void Language_preference_is_saved()
    {
        var settings = new AppSettings();
        var vm = new PreferencesViewModel(settings);
        Assert.Null(vm.UiLanguage.Value);

        vm.UiLanguage = PreferencesViewModel.UiLanguages.Single(l => l.Value == "es");
        vm.AcceptCommand.Execute(null);
        Assert.Equal("es", settings.UiCulture);
        Assert.Equal("es", new PreferencesViewModel(settings).UiLanguage.Value);
    }
}
