<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MMW.Formats.Ogg</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MMW.Core\MMW.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MMW.Media.Remux.Tests" />
  </ItemGroup>
</Project>
