<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MMW.Queue</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MMW.Core\MMW.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MMW.Queue.Tests" />
  </ItemGroup>
</Project>
