<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MMW.Formats.Elementary</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MMW.Core\MMW.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="MMW.Formats.Elementary.Tests" />
  </ItemGroup>
</Project>
