<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MMW.Metadata</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MMW.Metadata.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MMW.Core\MMW.Core.csproj" />
  </ItemGroup>
</Project>
